-- 1. Tabla de Perfiles de Usuario
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  nombre TEXT,
  correo TEXT,
  edad INTEGER,
  barrio_comunidad TEXT,
  es_fumador BOOLEAN DEFAULT false,
  puntos INTEGER DEFAULT 0,
  nivel TEXT DEFAULT 'Protector Dental',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Encuestas
CREATE TABLE surveys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  tipo_encuesta TEXT,
  respuestas JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabla de Retos
CREATE TABLE challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT,
  descripcion TEXT,
  puntos INTEGER,
  icono TEXT,
  color TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabla de Progreso en Juegos
CREATE TABLE games_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  juego TEXT,
  puntos_ganados INTEGER,
  score INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabla de Retos de Usuario (Para marcar completados)
CREATE TABLE user_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  challenge_id BIGINT REFERENCES challenges ON DELETE CASCADE,
  completado BOOLEAN DEFAULT false,
  fecha_completado TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE games_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_challenges ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (Permitir a usuarios ver y editar su propio perfil)
CREATE POLICY "Usuarios pueden ver su propio perfil" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Usuarios pueden actualizar su propio perfil" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Cualquiera puede ver los retos" ON challenges FOR SELECT USING (true);
CREATE POLICY "Usuarios pueden ver sus propias encuestas" ON surveys FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Usuarios pueden insertar sus encuestas" ON surveys FOR INSERT WITH CHECK (auth.uid() = user_id);